// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: highscore.proto

package com.leruka.protobuf;

public final class Highscore {
  private Highscore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestGlobalScoresOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.RequestGlobalScores)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string levelName = 1;</code>
     */
    String getLevelName();
    /**
     * <code>optional string levelName = 1;</code>
     */
    com.google.protobuf.ByteString
        getLevelNameBytes();

    /**
     * <code>optional uint64 fromRank = 2;</code>
     */
    long getFromRank();

    /**
     * <code>optional uint64 toRank = 3;</code>
     */
    long getToRank();
  }
  /**
   * Protobuf type {@code leruka.RequestGlobalScores}
   */
  public  static final class RequestGlobalScores extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.RequestGlobalScores)
      RequestGlobalScoresOrBuilder {
    // Use RequestGlobalScores.newBuilder() to construct.
    private RequestGlobalScores(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RequestGlobalScores() {
      levelName_ = "";
      fromRank_ = 0L;
      toRank_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestGlobalScores(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              levelName_ = s;
              break;
            }
            case 16: {

              fromRank_ = input.readUInt64();
              break;
            }
            case 24: {

              toRank_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Highscore.internal_static_leruka_RequestGlobalScores_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Highscore.internal_static_leruka_RequestGlobalScores_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestGlobalScores.class, Builder.class);
    }

    public static final int LEVELNAME_FIELD_NUMBER = 1;
    private volatile Object levelName_;
    /**
     * <code>optional string levelName = 1;</code>
     */
    public String getLevelName() {
      Object ref = levelName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        levelName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string levelName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLevelNameBytes() {
      Object ref = levelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        levelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMRANK_FIELD_NUMBER = 2;
    private long fromRank_;
    /**
     * <code>optional uint64 fromRank = 2;</code>
     */
    public long getFromRank() {
      return fromRank_;
    }

    public static final int TORANK_FIELD_NUMBER = 3;
    private long toRank_;
    /**
     * <code>optional uint64 toRank = 3;</code>
     */
    public long getToRank() {
      return toRank_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLevelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, levelName_);
      }
      if (fromRank_ != 0L) {
        output.writeUInt64(2, fromRank_);
      }
      if (toRank_ != 0L) {
        output.writeUInt64(3, toRank_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLevelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, levelName_);
      }
      if (fromRank_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, fromRank_);
      }
      if (toRank_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, toRank_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static RequestGlobalScores parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestGlobalScores parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestGlobalScores parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestGlobalScores parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestGlobalScores parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestGlobalScores parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RequestGlobalScores parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RequestGlobalScores parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RequestGlobalScores parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestGlobalScores parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestGlobalScores prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.RequestGlobalScores}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.RequestGlobalScores)
        RequestGlobalScoresOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Highscore.internal_static_leruka_RequestGlobalScores_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Highscore.internal_static_leruka_RequestGlobalScores_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestGlobalScores.class, Builder.class);
      }

      // Construct using com.leruka.protobuf.Highscore.RequestGlobalScores.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        levelName_ = "";

        fromRank_ = 0L;

        toRank_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Highscore.internal_static_leruka_RequestGlobalScores_descriptor;
      }

      public RequestGlobalScores getDefaultInstanceForType() {
        return RequestGlobalScores.getDefaultInstance();
      }

      public RequestGlobalScores build() {
        RequestGlobalScores result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestGlobalScores buildPartial() {
        RequestGlobalScores result = new RequestGlobalScores(this);
        result.levelName_ = levelName_;
        result.fromRank_ = fromRank_;
        result.toRank_ = toRank_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestGlobalScores) {
          return mergeFrom((RequestGlobalScores)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestGlobalScores other) {
        if (other == RequestGlobalScores.getDefaultInstance()) return this;
        if (!other.getLevelName().isEmpty()) {
          levelName_ = other.levelName_;
          onChanged();
        }
        if (other.getFromRank() != 0L) {
          setFromRank(other.getFromRank());
        }
        if (other.getToRank() != 0L) {
          setToRank(other.getToRank());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestGlobalScores parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestGlobalScores) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object levelName_ = "";
      /**
       * <code>optional string levelName = 1;</code>
       */
      public String getLevelName() {
        Object ref = levelName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          levelName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLevelNameBytes() {
        Object ref = levelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          levelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder setLevelName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        levelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder clearLevelName() {
        
        levelName_ = getDefaultInstance().getLevelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder setLevelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        levelName_ = value;
        onChanged();
        return this;
      }

      private long fromRank_ ;
      /**
       * <code>optional uint64 fromRank = 2;</code>
       */
      public long getFromRank() {
        return fromRank_;
      }
      /**
       * <code>optional uint64 fromRank = 2;</code>
       */
      public Builder setFromRank(long value) {
        
        fromRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 fromRank = 2;</code>
       */
      public Builder clearFromRank() {
        
        fromRank_ = 0L;
        onChanged();
        return this;
      }

      private long toRank_ ;
      /**
       * <code>optional uint64 toRank = 3;</code>
       */
      public long getToRank() {
        return toRank_;
      }
      /**
       * <code>optional uint64 toRank = 3;</code>
       */
      public Builder setToRank(long value) {
        
        toRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 toRank = 3;</code>
       */
      public Builder clearToRank() {
        
        toRank_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.RequestGlobalScores)
    }

    // @@protoc_insertion_point(class_scope:leruka.RequestGlobalScores)
    private static final RequestGlobalScores DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestGlobalScores();
    }

    public static RequestGlobalScores getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestGlobalScores>
        PARSER = new com.google.protobuf.AbstractParser<RequestGlobalScores>() {
      public RequestGlobalScores parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RequestGlobalScores(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RequestGlobalScores> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestGlobalScores> getParserForType() {
      return PARSER;
    }

    public RequestGlobalScores getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestPrivateScoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.RequestPrivateScore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string sessionID = 1;</code>
     */
    String getSessionID();
    /**
     * <code>optional string sessionID = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionIDBytes();

    /**
     * <code>optional string levelName = 2;</code>
     */
    String getLevelName();
    /**
     * <code>optional string levelName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLevelNameBytes();
  }
  /**
   * Protobuf type {@code leruka.RequestPrivateScore}
   */
  public  static final class RequestPrivateScore extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.RequestPrivateScore)
      RequestPrivateScoreOrBuilder {
    // Use RequestPrivateScore.newBuilder() to construct.
    private RequestPrivateScore(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RequestPrivateScore() {
      sessionID_ = "";
      levelName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestPrivateScore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              sessionID_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              levelName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Highscore.internal_static_leruka_RequestPrivateScore_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Highscore.internal_static_leruka_RequestPrivateScore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestPrivateScore.class, Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private volatile Object sessionID_;
    /**
     * <code>optional string sessionID = 1;</code>
     */
    public String getSessionID() {
      Object ref = sessionID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sessionID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sessionID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIDBytes() {
      Object ref = sessionID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVELNAME_FIELD_NUMBER = 2;
    private volatile Object levelName_;
    /**
     * <code>optional string levelName = 2;</code>
     */
    public String getLevelName() {
      Object ref = levelName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        levelName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string levelName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLevelNameBytes() {
      Object ref = levelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        levelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSessionIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionID_);
      }
      if (!getLevelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, levelName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionID_);
      }
      if (!getLevelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, levelName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static RequestPrivateScore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestPrivateScore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestPrivateScore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestPrivateScore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestPrivateScore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestPrivateScore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RequestPrivateScore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RequestPrivateScore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RequestPrivateScore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestPrivateScore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestPrivateScore prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.RequestPrivateScore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.RequestPrivateScore)
        RequestPrivateScoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Highscore.internal_static_leruka_RequestPrivateScore_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Highscore.internal_static_leruka_RequestPrivateScore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestPrivateScore.class, Builder.class);
      }

      // Construct using com.leruka.protobuf.Highscore.RequestPrivateScore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sessionID_ = "";

        levelName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Highscore.internal_static_leruka_RequestPrivateScore_descriptor;
      }

      public RequestPrivateScore getDefaultInstanceForType() {
        return RequestPrivateScore.getDefaultInstance();
      }

      public RequestPrivateScore build() {
        RequestPrivateScore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestPrivateScore buildPartial() {
        RequestPrivateScore result = new RequestPrivateScore(this);
        result.sessionID_ = sessionID_;
        result.levelName_ = levelName_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestPrivateScore) {
          return mergeFrom((RequestPrivateScore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestPrivateScore other) {
        if (other == RequestPrivateScore.getDefaultInstance()) return this;
        if (!other.getSessionID().isEmpty()) {
          sessionID_ = other.sessionID_;
          onChanged();
        }
        if (!other.getLevelName().isEmpty()) {
          levelName_ = other.levelName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestPrivateScore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestPrivateScore) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object sessionID_ = "";
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public String getSessionID() {
        Object ref = sessionID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sessionID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIDBytes() {
        Object ref = sessionID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public Builder setSessionID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public Builder clearSessionID() {
        
        sessionID_ = getDefaultInstance().getSessionID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public Builder setSessionIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionID_ = value;
        onChanged();
        return this;
      }

      private Object levelName_ = "";
      /**
       * <code>optional string levelName = 2;</code>
       */
      public String getLevelName() {
        Object ref = levelName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          levelName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLevelNameBytes() {
        Object ref = levelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          levelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public Builder setLevelName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        levelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public Builder clearLevelName() {
        
        levelName_ = getDefaultInstance().getLevelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public Builder setLevelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        levelName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.RequestPrivateScore)
    }

    // @@protoc_insertion_point(class_scope:leruka.RequestPrivateScore)
    private static final RequestPrivateScore DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestPrivateScore();
    }

    public static RequestPrivateScore getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestPrivateScore>
        PARSER = new com.google.protobuf.AbstractParser<RequestPrivateScore>() {
      public RequestPrivateScore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RequestPrivateScore(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RequestPrivateScore> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestPrivateScore> getParserForType() {
      return PARSER;
    }

    public RequestPrivateScore getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseScoresOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.ResponseScores)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string levelName = 1;</code>
     */
    String getLevelName();
    /**
     * <code>optional string levelName = 1;</code>
     */
    com.google.protobuf.ByteString
        getLevelNameBytes();

    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    java.util.List<Score>
        getScoresList();
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    Score getScores(int index);
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    int getScoresCount();
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    java.util.List<? extends ScoreOrBuilder>
        getScoresOrBuilderList();
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    ScoreOrBuilder getScoresOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code leruka.ResponseScores}
   */
  public  static final class ResponseScores extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.ResponseScores)
      ResponseScoresOrBuilder {
    // Use ResponseScores.newBuilder() to construct.
    private ResponseScores(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResponseScores() {
      levelName_ = "";
      scores_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseScores(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              levelName_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                scores_ = new java.util.ArrayList<Score>();
                mutable_bitField0_ |= 0x00000002;
              }
              scores_.add(input.readMessage(Score.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Highscore.internal_static_leruka_ResponseScores_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Highscore.internal_static_leruka_ResponseScores_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseScores.class, Builder.class);
    }

    private int bitField0_;
    public static final int LEVELNAME_FIELD_NUMBER = 1;
    private volatile Object levelName_;
    /**
     * <code>optional string levelName = 1;</code>
     */
    public String getLevelName() {
      Object ref = levelName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        levelName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string levelName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLevelNameBytes() {
      Object ref = levelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        levelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORES_FIELD_NUMBER = 2;
    private java.util.List<Score> scores_;
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public java.util.List<Score> getScoresList() {
      return scores_;
    }
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public java.util.List<? extends ScoreOrBuilder>
        getScoresOrBuilderList() {
      return scores_;
    }
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public int getScoresCount() {
      return scores_.size();
    }
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public Score getScores(int index) {
      return scores_.get(index);
    }
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public ScoreOrBuilder getScoresOrBuilder(
        int index) {
      return scores_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLevelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, levelName_);
      }
      for (int i = 0; i < scores_.size(); i++) {
        output.writeMessage(2, scores_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLevelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, levelName_);
      }
      for (int i = 0; i < scores_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, scores_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ResponseScores parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseScores parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseScores parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseScores parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseScores parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseScores parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ResponseScores parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ResponseScores parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ResponseScores parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseScores parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResponseScores prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.ResponseScores}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.ResponseScores)
        ResponseScoresOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Highscore.internal_static_leruka_ResponseScores_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Highscore.internal_static_leruka_ResponseScores_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseScores.class, Builder.class);
      }

      // Construct using com.leruka.protobuf.Highscore.ResponseScores.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getScoresFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        levelName_ = "";

        if (scoresBuilder_ == null) {
          scores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          scoresBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Highscore.internal_static_leruka_ResponseScores_descriptor;
      }

      public ResponseScores getDefaultInstanceForType() {
        return ResponseScores.getDefaultInstance();
      }

      public ResponseScores build() {
        ResponseScores result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResponseScores buildPartial() {
        ResponseScores result = new ResponseScores(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.levelName_ = levelName_;
        if (scoresBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            scores_ = java.util.Collections.unmodifiableList(scores_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.scores_ = scores_;
        } else {
          result.scores_ = scoresBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseScores) {
          return mergeFrom((ResponseScores)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseScores other) {
        if (other == ResponseScores.getDefaultInstance()) return this;
        if (!other.getLevelName().isEmpty()) {
          levelName_ = other.levelName_;
          onChanged();
        }
        if (scoresBuilder_ == null) {
          if (!other.scores_.isEmpty()) {
            if (scores_.isEmpty()) {
              scores_ = other.scores_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureScoresIsMutable();
              scores_.addAll(other.scores_);
            }
            onChanged();
          }
        } else {
          if (!other.scores_.isEmpty()) {
            if (scoresBuilder_.isEmpty()) {
              scoresBuilder_.dispose();
              scoresBuilder_ = null;
              scores_ = other.scores_;
              bitField0_ = (bitField0_ & ~0x00000002);
              scoresBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getScoresFieldBuilder() : null;
            } else {
              scoresBuilder_.addAllMessages(other.scores_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseScores parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseScores) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object levelName_ = "";
      /**
       * <code>optional string levelName = 1;</code>
       */
      public String getLevelName() {
        Object ref = levelName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          levelName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLevelNameBytes() {
        Object ref = levelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          levelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder setLevelName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        levelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder clearLevelName() {
        
        levelName_ = getDefaultInstance().getLevelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder setLevelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        levelName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Score> scores_ =
        java.util.Collections.emptyList();
      private void ensureScoresIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          scores_ = new java.util.ArrayList<Score>(scores_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Score, Score.Builder, ScoreOrBuilder> scoresBuilder_;

      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public java.util.List<Score> getScoresList() {
        if (scoresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(scores_);
        } else {
          return scoresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public int getScoresCount() {
        if (scoresBuilder_ == null) {
          return scores_.size();
        } else {
          return scoresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Score getScores(int index) {
        if (scoresBuilder_ == null) {
          return scores_.get(index);
        } else {
          return scoresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder setScores(
          int index, Score value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.set(index, value);
          onChanged();
        } else {
          scoresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder setScores(
          int index, Score.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.set(index, builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addScores(Score value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.add(value);
          onChanged();
        } else {
          scoresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addScores(
          int index, Score value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.add(index, value);
          onChanged();
        } else {
          scoresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addScores(
          Score.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.add(builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addScores(
          int index, Score.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.add(index, builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addAllScores(
          Iterable<? extends Score> values) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, scores_);
          onChanged();
        } else {
          scoresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder clearScores() {
        if (scoresBuilder_ == null) {
          scores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          scoresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder removeScores(int index) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.remove(index);
          onChanged();
        } else {
          scoresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Score.Builder getScoresBuilder(
          int index) {
        return getScoresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public ScoreOrBuilder getScoresOrBuilder(
          int index) {
        if (scoresBuilder_ == null) {
          return scores_.get(index);  } else {
          return scoresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public java.util.List<? extends ScoreOrBuilder>
           getScoresOrBuilderList() {
        if (scoresBuilder_ != null) {
          return scoresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(scores_);
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Score.Builder addScoresBuilder() {
        return getScoresFieldBuilder().addBuilder(
            Score.getDefaultInstance());
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Score.Builder addScoresBuilder(
          int index) {
        return getScoresFieldBuilder().addBuilder(
            index, Score.getDefaultInstance());
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public java.util.List<Score.Builder>
           getScoresBuilderList() {
        return getScoresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Score, Score.Builder, ScoreOrBuilder>
          getScoresFieldBuilder() {
        if (scoresBuilder_ == null) {
          scoresBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Score, Score.Builder, ScoreOrBuilder>(
                  scores_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          scores_ = null;
        }
        return scoresBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.ResponseScores)
    }

    // @@protoc_insertion_point(class_scope:leruka.ResponseScores)
    private static final ResponseScores DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResponseScores();
    }

    public static ResponseScores getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseScores>
        PARSER = new com.google.protobuf.AbstractParser<ResponseScores>() {
      public ResponseScores parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ResponseScores(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ResponseScores> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResponseScores> getParserForType() {
      return PARSER;
    }

    public ResponseScores getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.Score)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string userName = 1;</code>
     */
    String getUserName();
    /**
     * <code>optional string userName = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional uint64 rank = 2;</code>
     */
    long getRank();

    /**
     * <code>optional uint64 score = 3;</code>
     */
    long getScore();

    /**
     * <code>optional uint64 timestamp = 4;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code leruka.Score}
   */
  public  static final class Score extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.Score)
      ScoreOrBuilder {
    // Use Score.newBuilder() to construct.
    private Score(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Score() {
      userName_ = "";
      rank_ = 0L;
      score_ = 0L;
      timestamp_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Score(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 16: {

              rank_ = input.readUInt64();
              break;
            }
            case 24: {

              score_ = input.readUInt64();
              break;
            }
            case 32: {

              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Highscore.internal_static_leruka_Score_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Highscore.internal_static_leruka_Score_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Score.class, Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile Object userName_;
    /**
     * <code>optional string userName = 1;</code>
     */
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RANK_FIELD_NUMBER = 2;
    private long rank_;
    /**
     * <code>optional uint64 rank = 2;</code>
     */
    public long getRank() {
      return rank_;
    }

    public static final int SCORE_FIELD_NUMBER = 3;
    private long score_;
    /**
     * <code>optional uint64 score = 3;</code>
     */
    public long getScore() {
      return score_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, userName_);
      }
      if (rank_ != 0L) {
        output.writeUInt64(2, rank_);
      }
      if (score_ != 0L) {
        output.writeUInt64(3, score_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(4, timestamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userName_);
      }
      if (rank_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, rank_);
      }
      if (score_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, score_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, timestamp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Score parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Score parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Score parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Score parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Score parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Score parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Score parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Score parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Score parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Score parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Score prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.Score}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.Score)
        ScoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Highscore.internal_static_leruka_Score_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Highscore.internal_static_leruka_Score_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Score.class, Builder.class);
      }

      // Construct using com.leruka.protobuf.Highscore.Score.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userName_ = "";

        rank_ = 0L;

        score_ = 0L;

        timestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Highscore.internal_static_leruka_Score_descriptor;
      }

      public Score getDefaultInstanceForType() {
        return Score.getDefaultInstance();
      }

      public Score build() {
        Score result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Score buildPartial() {
        Score result = new Score(this);
        result.userName_ = userName_;
        result.rank_ = rank_;
        result.score_ = score_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Score) {
          return mergeFrom((Score)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Score other) {
        if (other == Score.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (other.getRank() != 0L) {
          setRank(other.getRank());
        }
        if (other.getScore() != 0L) {
          setScore(other.getScore());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Score parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Score) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object userName_ = "";
      /**
       * <code>optional string userName = 1;</code>
       */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private long rank_ ;
      /**
       * <code>optional uint64 rank = 2;</code>
       */
      public long getRank() {
        return rank_;
      }
      /**
       * <code>optional uint64 rank = 2;</code>
       */
      public Builder setRank(long value) {
        
        rank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 rank = 2;</code>
       */
      public Builder clearRank() {
        
        rank_ = 0L;
        onChanged();
        return this;
      }

      private long score_ ;
      /**
       * <code>optional uint64 score = 3;</code>
       */
      public long getScore() {
        return score_;
      }
      /**
       * <code>optional uint64 score = 3;</code>
       */
      public Builder setScore(long value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 score = 3;</code>
       */
      public Builder clearScore() {
        
        score_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.Score)
    }

    // @@protoc_insertion_point(class_scope:leruka.Score)
    private static final Score DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Score();
    }

    public static Score getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Score>
        PARSER = new com.google.protobuf.AbstractParser<Score>() {
      public Score parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Score(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Score> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Score> getParserForType() {
      return PARSER;
    }

    public Score getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_RequestGlobalScores_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_RequestGlobalScores_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_RequestPrivateScore_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_RequestPrivateScore_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_ResponseScores_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_ResponseScores_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_Score_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_Score_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017highscore.proto\022\006leruka\"J\n\023RequestGlob" +
      "alScores\022\021\n\tlevelName\030\001 \001(\t\022\020\n\010fromRank\030" +
      "\002 \001(\004\022\016\n\006toRank\030\003 \001(\004\";\n\023RequestPrivateS" +
      "core\022\021\n\tsessionID\030\001 \001(\t\022\021\n\tlevelName\030\002 \001" +
      "(\t\"B\n\016ResponseScores\022\021\n\tlevelName\030\001 \001(\t\022" +
      "\035\n\006scores\030\002 \003(\0132\r.leruka.Score\"I\n\005Score\022" +
      "\020\n\010userName\030\001 \001(\t\022\014\n\004rank\030\002 \001(\004\022\r\n\005score" +
      "\030\003 \001(\004\022\021\n\ttimestamp\030\004 \001(\004B\025\n\023com.leruka." +
      "protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_leruka_RequestGlobalScores_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_leruka_RequestGlobalScores_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_RequestGlobalScores_descriptor,
        new String[] { "LevelName", "FromRank", "ToRank", });
    internal_static_leruka_RequestPrivateScore_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_leruka_RequestPrivateScore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_RequestPrivateScore_descriptor,
        new String[] { "SessionID", "LevelName", });
    internal_static_leruka_ResponseScores_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_leruka_ResponseScores_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_ResponseScores_descriptor,
        new String[] { "LevelName", "Scores", });
    internal_static_leruka_Score_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_leruka_Score_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_Score_descriptor,
        new String[] { "UserName", "Rank", "Score", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
