// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: highscore.proto

package com.leruka.protobuf;

public final class Highscore {
  private Highscore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestGlobalScoresOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.RequestGlobalScores)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string levelName = 1;</code>
     */
    java.lang.String getLevelName();
    /**
     * <code>optional string levelName = 1;</code>
     */
    com.google.protobuf.ByteString
        getLevelNameBytes();

    /**
     * <code>optional uint64 fromRank = 2;</code>
     */
    long getFromRank();

    /**
     * <code>optional uint64 toRank = 3;</code>
     */
    long getToRank();
  }
  /**
   * Protobuf type {@code leruka.RequestGlobalScores}
   */
  public  static final class RequestGlobalScores extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.RequestGlobalScores)
      RequestGlobalScoresOrBuilder {
    // Use RequestGlobalScores.newBuilder() to construct.
    private RequestGlobalScores(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RequestGlobalScores() {
      levelName_ = "";
      fromRank_ = 0L;
      toRank_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestGlobalScores(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              levelName_ = s;
              break;
            }
            case 16: {

              fromRank_ = input.readUInt64();
              break;
            }
            case 24: {

              toRank_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leruka.protobuf.Highscore.internal_static_leruka_RequestGlobalScores_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leruka.protobuf.Highscore.internal_static_leruka_RequestGlobalScores_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leruka.protobuf.Highscore.RequestGlobalScores.class, com.leruka.protobuf.Highscore.RequestGlobalScores.Builder.class);
    }

    public static final int LEVELNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object levelName_;
    /**
     * <code>optional string levelName = 1;</code>
     */
    public java.lang.String getLevelName() {
      java.lang.Object ref = levelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        levelName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string levelName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLevelNameBytes() {
      java.lang.Object ref = levelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        levelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMRANK_FIELD_NUMBER = 2;
    private long fromRank_;
    /**
     * <code>optional uint64 fromRank = 2;</code>
     */
    public long getFromRank() {
      return fromRank_;
    }

    public static final int TORANK_FIELD_NUMBER = 3;
    private long toRank_;
    /**
     * <code>optional uint64 toRank = 3;</code>
     */
    public long getToRank() {
      return toRank_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLevelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, levelName_);
      }
      if (fromRank_ != 0L) {
        output.writeUInt64(2, fromRank_);
      }
      if (toRank_ != 0L) {
        output.writeUInt64(3, toRank_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLevelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, levelName_);
      }
      if (fromRank_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, fromRank_);
      }
      if (toRank_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, toRank_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.Highscore.RequestGlobalScores parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leruka.protobuf.Highscore.RequestGlobalScores prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.RequestGlobalScores}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.RequestGlobalScores)
        com.leruka.protobuf.Highscore.RequestGlobalScoresOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_RequestGlobalScores_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_RequestGlobalScores_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leruka.protobuf.Highscore.RequestGlobalScores.class, com.leruka.protobuf.Highscore.RequestGlobalScores.Builder.class);
      }

      // Construct using com.leruka.protobuf.Highscore.RequestGlobalScores.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        levelName_ = "";

        fromRank_ = 0L;

        toRank_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_RequestGlobalScores_descriptor;
      }

      public com.leruka.protobuf.Highscore.RequestGlobalScores getDefaultInstanceForType() {
        return com.leruka.protobuf.Highscore.RequestGlobalScores.getDefaultInstance();
      }

      public com.leruka.protobuf.Highscore.RequestGlobalScores build() {
        com.leruka.protobuf.Highscore.RequestGlobalScores result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leruka.protobuf.Highscore.RequestGlobalScores buildPartial() {
        com.leruka.protobuf.Highscore.RequestGlobalScores result = new com.leruka.protobuf.Highscore.RequestGlobalScores(this);
        result.levelName_ = levelName_;
        result.fromRank_ = fromRank_;
        result.toRank_ = toRank_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leruka.protobuf.Highscore.RequestGlobalScores) {
          return mergeFrom((com.leruka.protobuf.Highscore.RequestGlobalScores)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leruka.protobuf.Highscore.RequestGlobalScores other) {
        if (other == com.leruka.protobuf.Highscore.RequestGlobalScores.getDefaultInstance()) return this;
        if (!other.getLevelName().isEmpty()) {
          levelName_ = other.levelName_;
          onChanged();
        }
        if (other.getFromRank() != 0L) {
          setFromRank(other.getFromRank());
        }
        if (other.getToRank() != 0L) {
          setToRank(other.getToRank());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leruka.protobuf.Highscore.RequestGlobalScores parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leruka.protobuf.Highscore.RequestGlobalScores) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object levelName_ = "";
      /**
       * <code>optional string levelName = 1;</code>
       */
      public java.lang.String getLevelName() {
        java.lang.Object ref = levelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          levelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLevelNameBytes() {
        java.lang.Object ref = levelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          levelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder setLevelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        levelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder clearLevelName() {
        
        levelName_ = getDefaultInstance().getLevelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder setLevelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        levelName_ = value;
        onChanged();
        return this;
      }

      private long fromRank_ ;
      /**
       * <code>optional uint64 fromRank = 2;</code>
       */
      public long getFromRank() {
        return fromRank_;
      }
      /**
       * <code>optional uint64 fromRank = 2;</code>
       */
      public Builder setFromRank(long value) {
        
        fromRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 fromRank = 2;</code>
       */
      public Builder clearFromRank() {
        
        fromRank_ = 0L;
        onChanged();
        return this;
      }

      private long toRank_ ;
      /**
       * <code>optional uint64 toRank = 3;</code>
       */
      public long getToRank() {
        return toRank_;
      }
      /**
       * <code>optional uint64 toRank = 3;</code>
       */
      public Builder setToRank(long value) {
        
        toRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 toRank = 3;</code>
       */
      public Builder clearToRank() {
        
        toRank_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.RequestGlobalScores)
    }

    // @@protoc_insertion_point(class_scope:leruka.RequestGlobalScores)
    private static final com.leruka.protobuf.Highscore.RequestGlobalScores DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leruka.protobuf.Highscore.RequestGlobalScores();
    }

    public static com.leruka.protobuf.Highscore.RequestGlobalScores getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestGlobalScores>
        PARSER = new com.google.protobuf.AbstractParser<RequestGlobalScores>() {
      public RequestGlobalScores parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RequestGlobalScores(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RequestGlobalScores> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestGlobalScores> getParserForType() {
      return PARSER;
    }

    public com.leruka.protobuf.Highscore.RequestGlobalScores getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestPushScoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.RequestPushScore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string sessionID = 1;</code>
     */
    java.lang.String getSessionID();
    /**
     * <code>optional string sessionID = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionIDBytes();

    /**
     * <code>optional string levelName = 2;</code>
     */
    java.lang.String getLevelName();
    /**
     * <code>optional string levelName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLevelNameBytes();
  }
  /**
   * Protobuf type {@code leruka.RequestPushScore}
   */
  public  static final class RequestPushScore extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.RequestPushScore)
      RequestPushScoreOrBuilder {
    // Use RequestPushScore.newBuilder() to construct.
    private RequestPushScore(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RequestPushScore() {
      sessionID_ = "";
      levelName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestPushScore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionID_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              levelName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leruka.protobuf.Highscore.internal_static_leruka_RequestPushScore_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leruka.protobuf.Highscore.internal_static_leruka_RequestPushScore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leruka.protobuf.Highscore.RequestPushScore.class, com.leruka.protobuf.Highscore.RequestPushScore.Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sessionID_;
    /**
     * <code>optional string sessionID = 1;</code>
     */
    public java.lang.String getSessionID() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sessionID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIDBytes() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVELNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object levelName_;
    /**
     * <code>optional string levelName = 2;</code>
     */
    public java.lang.String getLevelName() {
      java.lang.Object ref = levelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        levelName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string levelName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLevelNameBytes() {
      java.lang.Object ref = levelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        levelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSessionIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionID_);
      }
      if (!getLevelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, levelName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionID_);
      }
      if (!getLevelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, levelName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.leruka.protobuf.Highscore.RequestPushScore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.Highscore.RequestPushScore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.RequestPushScore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.Highscore.RequestPushScore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.RequestPushScore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.Highscore.RequestPushScore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.RequestPushScore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leruka.protobuf.Highscore.RequestPushScore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.RequestPushScore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.Highscore.RequestPushScore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leruka.protobuf.Highscore.RequestPushScore prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.RequestPushScore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.RequestPushScore)
        com.leruka.protobuf.Highscore.RequestPushScoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_RequestPushScore_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_RequestPushScore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leruka.protobuf.Highscore.RequestPushScore.class, com.leruka.protobuf.Highscore.RequestPushScore.Builder.class);
      }

      // Construct using com.leruka.protobuf.Highscore.RequestPushScore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sessionID_ = "";

        levelName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_RequestPushScore_descriptor;
      }

      public com.leruka.protobuf.Highscore.RequestPushScore getDefaultInstanceForType() {
        return com.leruka.protobuf.Highscore.RequestPushScore.getDefaultInstance();
      }

      public com.leruka.protobuf.Highscore.RequestPushScore build() {
        com.leruka.protobuf.Highscore.RequestPushScore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leruka.protobuf.Highscore.RequestPushScore buildPartial() {
        com.leruka.protobuf.Highscore.RequestPushScore result = new com.leruka.protobuf.Highscore.RequestPushScore(this);
        result.sessionID_ = sessionID_;
        result.levelName_ = levelName_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leruka.protobuf.Highscore.RequestPushScore) {
          return mergeFrom((com.leruka.protobuf.Highscore.RequestPushScore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leruka.protobuf.Highscore.RequestPushScore other) {
        if (other == com.leruka.protobuf.Highscore.RequestPushScore.getDefaultInstance()) return this;
        if (!other.getSessionID().isEmpty()) {
          sessionID_ = other.sessionID_;
          onChanged();
        }
        if (!other.getLevelName().isEmpty()) {
          levelName_ = other.levelName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leruka.protobuf.Highscore.RequestPushScore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leruka.protobuf.Highscore.RequestPushScore) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sessionID_ = "";
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public java.lang.String getSessionID() {
        java.lang.Object ref = sessionID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIDBytes() {
        java.lang.Object ref = sessionID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public Builder setSessionID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public Builder clearSessionID() {
        
        sessionID_ = getDefaultInstance().getSessionID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public Builder setSessionIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object levelName_ = "";
      /**
       * <code>optional string levelName = 2;</code>
       */
      public java.lang.String getLevelName() {
        java.lang.Object ref = levelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          levelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLevelNameBytes() {
        java.lang.Object ref = levelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          levelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public Builder setLevelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        levelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public Builder clearLevelName() {
        
        levelName_ = getDefaultInstance().getLevelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public Builder setLevelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        levelName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.RequestPushScore)
    }

    // @@protoc_insertion_point(class_scope:leruka.RequestPushScore)
    private static final com.leruka.protobuf.Highscore.RequestPushScore DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leruka.protobuf.Highscore.RequestPushScore();
    }

    public static com.leruka.protobuf.Highscore.RequestPushScore getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestPushScore>
        PARSER = new com.google.protobuf.AbstractParser<RequestPushScore>() {
      public RequestPushScore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RequestPushScore(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RequestPushScore> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestPushScore> getParserForType() {
      return PARSER;
    }

    public com.leruka.protobuf.Highscore.RequestPushScore getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseGlobalScoresOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.ResponseGlobalScores)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string levelName = 1;</code>
     */
    java.lang.String getLevelName();
    /**
     * <code>optional string levelName = 1;</code>
     */
    com.google.protobuf.ByteString
        getLevelNameBytes();

    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    java.util.List<com.leruka.protobuf.Highscore.Score> 
        getScoresList();
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    com.leruka.protobuf.Highscore.Score getScores(int index);
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    int getScoresCount();
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    java.util.List<? extends com.leruka.protobuf.Highscore.ScoreOrBuilder> 
        getScoresOrBuilderList();
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    com.leruka.protobuf.Highscore.ScoreOrBuilder getScoresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code leruka.ResponseGlobalScores}
   */
  public  static final class ResponseGlobalScores extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.ResponseGlobalScores)
      ResponseGlobalScoresOrBuilder {
    // Use ResponseGlobalScores.newBuilder() to construct.
    private ResponseGlobalScores(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResponseGlobalScores() {
      levelName_ = "";
      scores_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseGlobalScores(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              levelName_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                scores_ = new java.util.ArrayList<com.leruka.protobuf.Highscore.Score>();
                mutable_bitField0_ |= 0x00000002;
              }
              scores_.add(input.readMessage(com.leruka.protobuf.Highscore.Score.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leruka.protobuf.Highscore.internal_static_leruka_ResponseGlobalScores_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leruka.protobuf.Highscore.internal_static_leruka_ResponseGlobalScores_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leruka.protobuf.Highscore.ResponseGlobalScores.class, com.leruka.protobuf.Highscore.ResponseGlobalScores.Builder.class);
    }

    private int bitField0_;
    public static final int LEVELNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object levelName_;
    /**
     * <code>optional string levelName = 1;</code>
     */
    public java.lang.String getLevelName() {
      java.lang.Object ref = levelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        levelName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string levelName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLevelNameBytes() {
      java.lang.Object ref = levelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        levelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORES_FIELD_NUMBER = 2;
    private java.util.List<com.leruka.protobuf.Highscore.Score> scores_;
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public java.util.List<com.leruka.protobuf.Highscore.Score> getScoresList() {
      return scores_;
    }
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public java.util.List<? extends com.leruka.protobuf.Highscore.ScoreOrBuilder> 
        getScoresOrBuilderList() {
      return scores_;
    }
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public int getScoresCount() {
      return scores_.size();
    }
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public com.leruka.protobuf.Highscore.Score getScores(int index) {
      return scores_.get(index);
    }
    /**
     * <code>repeated .leruka.Score scores = 2;</code>
     */
    public com.leruka.protobuf.Highscore.ScoreOrBuilder getScoresOrBuilder(
        int index) {
      return scores_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLevelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, levelName_);
      }
      for (int i = 0; i < scores_.size(); i++) {
        output.writeMessage(2, scores_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLevelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, levelName_);
      }
      for (int i = 0; i < scores_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, scores_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.Highscore.ResponseGlobalScores parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leruka.protobuf.Highscore.ResponseGlobalScores prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.ResponseGlobalScores}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.ResponseGlobalScores)
        com.leruka.protobuf.Highscore.ResponseGlobalScoresOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_ResponseGlobalScores_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_ResponseGlobalScores_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leruka.protobuf.Highscore.ResponseGlobalScores.class, com.leruka.protobuf.Highscore.ResponseGlobalScores.Builder.class);
      }

      // Construct using com.leruka.protobuf.Highscore.ResponseGlobalScores.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getScoresFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        levelName_ = "";

        if (scoresBuilder_ == null) {
          scores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          scoresBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_ResponseGlobalScores_descriptor;
      }

      public com.leruka.protobuf.Highscore.ResponseGlobalScores getDefaultInstanceForType() {
        return com.leruka.protobuf.Highscore.ResponseGlobalScores.getDefaultInstance();
      }

      public com.leruka.protobuf.Highscore.ResponseGlobalScores build() {
        com.leruka.protobuf.Highscore.ResponseGlobalScores result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leruka.protobuf.Highscore.ResponseGlobalScores buildPartial() {
        com.leruka.protobuf.Highscore.ResponseGlobalScores result = new com.leruka.protobuf.Highscore.ResponseGlobalScores(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.levelName_ = levelName_;
        if (scoresBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            scores_ = java.util.Collections.unmodifiableList(scores_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.scores_ = scores_;
        } else {
          result.scores_ = scoresBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leruka.protobuf.Highscore.ResponseGlobalScores) {
          return mergeFrom((com.leruka.protobuf.Highscore.ResponseGlobalScores)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leruka.protobuf.Highscore.ResponseGlobalScores other) {
        if (other == com.leruka.protobuf.Highscore.ResponseGlobalScores.getDefaultInstance()) return this;
        if (!other.getLevelName().isEmpty()) {
          levelName_ = other.levelName_;
          onChanged();
        }
        if (scoresBuilder_ == null) {
          if (!other.scores_.isEmpty()) {
            if (scores_.isEmpty()) {
              scores_ = other.scores_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureScoresIsMutable();
              scores_.addAll(other.scores_);
            }
            onChanged();
          }
        } else {
          if (!other.scores_.isEmpty()) {
            if (scoresBuilder_.isEmpty()) {
              scoresBuilder_.dispose();
              scoresBuilder_ = null;
              scores_ = other.scores_;
              bitField0_ = (bitField0_ & ~0x00000002);
              scoresBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getScoresFieldBuilder() : null;
            } else {
              scoresBuilder_.addAllMessages(other.scores_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leruka.protobuf.Highscore.ResponseGlobalScores parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leruka.protobuf.Highscore.ResponseGlobalScores) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object levelName_ = "";
      /**
       * <code>optional string levelName = 1;</code>
       */
      public java.lang.String getLevelName() {
        java.lang.Object ref = levelName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          levelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLevelNameBytes() {
        java.lang.Object ref = levelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          levelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder setLevelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        levelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder clearLevelName() {
        
        levelName_ = getDefaultInstance().getLevelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 1;</code>
       */
      public Builder setLevelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        levelName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.leruka.protobuf.Highscore.Score> scores_ =
        java.util.Collections.emptyList();
      private void ensureScoresIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          scores_ = new java.util.ArrayList<com.leruka.protobuf.Highscore.Score>(scores_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.leruka.protobuf.Highscore.Score, com.leruka.protobuf.Highscore.Score.Builder, com.leruka.protobuf.Highscore.ScoreOrBuilder> scoresBuilder_;

      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public java.util.List<com.leruka.protobuf.Highscore.Score> getScoresList() {
        if (scoresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(scores_);
        } else {
          return scoresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public int getScoresCount() {
        if (scoresBuilder_ == null) {
          return scores_.size();
        } else {
          return scoresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public com.leruka.protobuf.Highscore.Score getScores(int index) {
        if (scoresBuilder_ == null) {
          return scores_.get(index);
        } else {
          return scoresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder setScores(
          int index, com.leruka.protobuf.Highscore.Score value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.set(index, value);
          onChanged();
        } else {
          scoresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder setScores(
          int index, com.leruka.protobuf.Highscore.Score.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.set(index, builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addScores(com.leruka.protobuf.Highscore.Score value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.add(value);
          onChanged();
        } else {
          scoresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addScores(
          int index, com.leruka.protobuf.Highscore.Score value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.add(index, value);
          onChanged();
        } else {
          scoresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addScores(
          com.leruka.protobuf.Highscore.Score.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.add(builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addScores(
          int index, com.leruka.protobuf.Highscore.Score.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.add(index, builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder addAllScores(
          java.lang.Iterable<? extends com.leruka.protobuf.Highscore.Score> values) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, scores_);
          onChanged();
        } else {
          scoresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder clearScores() {
        if (scoresBuilder_ == null) {
          scores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          scoresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public Builder removeScores(int index) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.remove(index);
          onChanged();
        } else {
          scoresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public com.leruka.protobuf.Highscore.Score.Builder getScoresBuilder(
          int index) {
        return getScoresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public com.leruka.protobuf.Highscore.ScoreOrBuilder getScoresOrBuilder(
          int index) {
        if (scoresBuilder_ == null) {
          return scores_.get(index);  } else {
          return scoresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public java.util.List<? extends com.leruka.protobuf.Highscore.ScoreOrBuilder> 
           getScoresOrBuilderList() {
        if (scoresBuilder_ != null) {
          return scoresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(scores_);
        }
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public com.leruka.protobuf.Highscore.Score.Builder addScoresBuilder() {
        return getScoresFieldBuilder().addBuilder(
            com.leruka.protobuf.Highscore.Score.getDefaultInstance());
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public com.leruka.protobuf.Highscore.Score.Builder addScoresBuilder(
          int index) {
        return getScoresFieldBuilder().addBuilder(
            index, com.leruka.protobuf.Highscore.Score.getDefaultInstance());
      }
      /**
       * <code>repeated .leruka.Score scores = 2;</code>
       */
      public java.util.List<com.leruka.protobuf.Highscore.Score.Builder> 
           getScoresBuilderList() {
        return getScoresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.leruka.protobuf.Highscore.Score, com.leruka.protobuf.Highscore.Score.Builder, com.leruka.protobuf.Highscore.ScoreOrBuilder> 
          getScoresFieldBuilder() {
        if (scoresBuilder_ == null) {
          scoresBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.leruka.protobuf.Highscore.Score, com.leruka.protobuf.Highscore.Score.Builder, com.leruka.protobuf.Highscore.ScoreOrBuilder>(
                  scores_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          scores_ = null;
        }
        return scoresBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.ResponseGlobalScores)
    }

    // @@protoc_insertion_point(class_scope:leruka.ResponseGlobalScores)
    private static final com.leruka.protobuf.Highscore.ResponseGlobalScores DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leruka.protobuf.Highscore.ResponseGlobalScores();
    }

    public static com.leruka.protobuf.Highscore.ResponseGlobalScores getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseGlobalScores>
        PARSER = new com.google.protobuf.AbstractParser<ResponseGlobalScores>() {
      public ResponseGlobalScores parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ResponseGlobalScores(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ResponseGlobalScores> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseGlobalScores> getParserForType() {
      return PARSER;
    }

    public com.leruka.protobuf.Highscore.ResponseGlobalScores getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.Score)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string userName = 1;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string userName = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional uint64 rank = 2;</code>
     */
    long getRank();

    /**
     * <code>optional uint64 score = 3;</code>
     */
    long getScore();
  }
  /**
   * Protobuf type {@code leruka.Score}
   */
  public  static final class Score extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.Score)
      ScoreOrBuilder {
    // Use Score.newBuilder() to construct.
    private Score(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Score() {
      userName_ = "";
      rank_ = 0L;
      score_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Score(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 16: {

              rank_ = input.readUInt64();
              break;
            }
            case 24: {

              score_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leruka.protobuf.Highscore.internal_static_leruka_Score_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leruka.protobuf.Highscore.internal_static_leruka_Score_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leruka.protobuf.Highscore.Score.class, com.leruka.protobuf.Highscore.Score.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object userName_;
    /**
     * <code>optional string userName = 1;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RANK_FIELD_NUMBER = 2;
    private long rank_;
    /**
     * <code>optional uint64 rank = 2;</code>
     */
    public long getRank() {
      return rank_;
    }

    public static final int SCORE_FIELD_NUMBER = 3;
    private long score_;
    /**
     * <code>optional uint64 score = 3;</code>
     */
    public long getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, userName_);
      }
      if (rank_ != 0L) {
        output.writeUInt64(2, rank_);
      }
      if (score_ != 0L) {
        output.writeUInt64(3, score_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userName_);
      }
      if (rank_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, rank_);
      }
      if (score_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, score_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.leruka.protobuf.Highscore.Score parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.Highscore.Score parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.Score parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.Highscore.Score parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.Score parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.Highscore.Score parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.Score parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leruka.protobuf.Highscore.Score parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.Highscore.Score parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.Highscore.Score parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leruka.protobuf.Highscore.Score prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.Score}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.Score)
        com.leruka.protobuf.Highscore.ScoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_Score_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_Score_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leruka.protobuf.Highscore.Score.class, com.leruka.protobuf.Highscore.Score.Builder.class);
      }

      // Construct using com.leruka.protobuf.Highscore.Score.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userName_ = "";

        rank_ = 0L;

        score_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leruka.protobuf.Highscore.internal_static_leruka_Score_descriptor;
      }

      public com.leruka.protobuf.Highscore.Score getDefaultInstanceForType() {
        return com.leruka.protobuf.Highscore.Score.getDefaultInstance();
      }

      public com.leruka.protobuf.Highscore.Score build() {
        com.leruka.protobuf.Highscore.Score result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leruka.protobuf.Highscore.Score buildPartial() {
        com.leruka.protobuf.Highscore.Score result = new com.leruka.protobuf.Highscore.Score(this);
        result.userName_ = userName_;
        result.rank_ = rank_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leruka.protobuf.Highscore.Score) {
          return mergeFrom((com.leruka.protobuf.Highscore.Score)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leruka.protobuf.Highscore.Score other) {
        if (other == com.leruka.protobuf.Highscore.Score.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (other.getRank() != 0L) {
          setRank(other.getRank());
        }
        if (other.getScore() != 0L) {
          setScore(other.getScore());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leruka.protobuf.Highscore.Score parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leruka.protobuf.Highscore.Score) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>optional string userName = 1;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 1;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private long rank_ ;
      /**
       * <code>optional uint64 rank = 2;</code>
       */
      public long getRank() {
        return rank_;
      }
      /**
       * <code>optional uint64 rank = 2;</code>
       */
      public Builder setRank(long value) {
        
        rank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 rank = 2;</code>
       */
      public Builder clearRank() {
        
        rank_ = 0L;
        onChanged();
        return this;
      }

      private long score_ ;
      /**
       * <code>optional uint64 score = 3;</code>
       */
      public long getScore() {
        return score_;
      }
      /**
       * <code>optional uint64 score = 3;</code>
       */
      public Builder setScore(long value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 score = 3;</code>
       */
      public Builder clearScore() {
        
        score_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.Score)
    }

    // @@protoc_insertion_point(class_scope:leruka.Score)
    private static final com.leruka.protobuf.Highscore.Score DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leruka.protobuf.Highscore.Score();
    }

    public static com.leruka.protobuf.Highscore.Score getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Score>
        PARSER = new com.google.protobuf.AbstractParser<Score>() {
      public Score parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Score(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Score> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Score> getParserForType() {
      return PARSER;
    }

    public com.leruka.protobuf.Highscore.Score getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_RequestGlobalScores_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_RequestGlobalScores_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_RequestPushScore_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_RequestPushScore_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_ResponseGlobalScores_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_ResponseGlobalScores_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_Score_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_Score_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017highscore.proto\022\006leruka\"J\n\023RequestGlob" +
      "alScores\022\021\n\tlevelName\030\001 \001(\t\022\020\n\010fromRank\030" +
      "\002 \001(\004\022\016\n\006toRank\030\003 \001(\004\"8\n\020RequestPushScor" +
      "e\022\021\n\tsessionID\030\001 \001(\t\022\021\n\tlevelName\030\002 \001(\t\"" +
      "H\n\024ResponseGlobalScores\022\021\n\tlevelName\030\001 \001" +
      "(\t\022\035\n\006scores\030\002 \003(\0132\r.leruka.Score\"6\n\005Sco" +
      "re\022\020\n\010userName\030\001 \001(\t\022\014\n\004rank\030\002 \001(\004\022\r\n\005sc" +
      "ore\030\003 \001(\004B\025\n\023com.leruka.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_leruka_RequestGlobalScores_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_leruka_RequestGlobalScores_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_RequestGlobalScores_descriptor,
        new java.lang.String[] { "LevelName", "FromRank", "ToRank", });
    internal_static_leruka_RequestPushScore_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_leruka_RequestPushScore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_RequestPushScore_descriptor,
        new java.lang.String[] { "SessionID", "LevelName", });
    internal_static_leruka_ResponseGlobalScores_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_leruka_ResponseGlobalScores_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_ResponseGlobalScores_descriptor,
        new java.lang.String[] { "LevelName", "Scores", });
    internal_static_leruka_Score_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_leruka_Score_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_Score_descriptor,
        new java.lang.String[] { "UserName", "Rank", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
