// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rating.proto

package com.leruka.protobuf;

public final class Rating {
  private Rating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestRateLevelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.RequestRateLevel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string sessionID = 1;</code>
     */
    String getSessionID();
    /**
     * <code>optional string sessionID = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessionIDBytes();

    /**
     * <code>optional string levelName = 2;</code>
     */
    String getLevelName();
    /**
     * <code>optional string levelName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLevelNameBytes();
  }
  /**
   * Protobuf type {@code leruka.RequestRateLevel}
   */
  public  static final class RequestRateLevel extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.RequestRateLevel)
      RequestRateLevelOrBuilder {
    // Use RequestRateLevel.newBuilder() to construct.
    private RequestRateLevel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RequestRateLevel() {
      sessionID_ = "";
      levelName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestRateLevel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              sessionID_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              levelName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Rating.internal_static_leruka_RequestRateLevel_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Rating.internal_static_leruka_RequestRateLevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestRateLevel.class, Builder.class);
    }

    public static final int SESSIONID_FIELD_NUMBER = 1;
    private volatile Object sessionID_;
    /**
     * <code>optional string sessionID = 1;</code>
     */
    public String getSessionID() {
      Object ref = sessionID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sessionID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sessionID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIDBytes() {
      Object ref = sessionID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVELNAME_FIELD_NUMBER = 2;
    private volatile Object levelName_;
    /**
     * <code>optional string levelName = 2;</code>
     */
    public String getLevelName() {
      Object ref = levelName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        levelName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string levelName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLevelNameBytes() {
      Object ref = levelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        levelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSessionIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionID_);
      }
      if (!getLevelNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, levelName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSessionIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionID_);
      }
      if (!getLevelNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, levelName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static RequestRateLevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestRateLevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestRateLevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestRateLevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestRateLevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestRateLevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RequestRateLevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RequestRateLevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RequestRateLevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RequestRateLevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestRateLevel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.RequestRateLevel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.RequestRateLevel)
        RequestRateLevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Rating.internal_static_leruka_RequestRateLevel_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Rating.internal_static_leruka_RequestRateLevel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestRateLevel.class, Builder.class);
      }

      // Construct using com.leruka.protobuf.Rating.RequestRateLevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sessionID_ = "";

        levelName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Rating.internal_static_leruka_RequestRateLevel_descriptor;
      }

      public RequestRateLevel getDefaultInstanceForType() {
        return RequestRateLevel.getDefaultInstance();
      }

      public RequestRateLevel build() {
        RequestRateLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RequestRateLevel buildPartial() {
        RequestRateLevel result = new RequestRateLevel(this);
        result.sessionID_ = sessionID_;
        result.levelName_ = levelName_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestRateLevel) {
          return mergeFrom((RequestRateLevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestRateLevel other) {
        if (other == RequestRateLevel.getDefaultInstance()) return this;
        if (!other.getSessionID().isEmpty()) {
          sessionID_ = other.sessionID_;
          onChanged();
        }
        if (!other.getLevelName().isEmpty()) {
          levelName_ = other.levelName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestRateLevel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestRateLevel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object sessionID_ = "";
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public String getSessionID() {
        Object ref = sessionID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sessionID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIDBytes() {
        Object ref = sessionID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public Builder setSessionID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public Builder clearSessionID() {
        
        sessionID_ = getDefaultInstance().getSessionID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionID = 1;</code>
       */
      public Builder setSessionIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionID_ = value;
        onChanged();
        return this;
      }

      private Object levelName_ = "";
      /**
       * <code>optional string levelName = 2;</code>
       */
      public String getLevelName() {
        Object ref = levelName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          levelName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLevelNameBytes() {
        Object ref = levelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          levelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public Builder setLevelName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        levelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public Builder clearLevelName() {
        
        levelName_ = getDefaultInstance().getLevelName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string levelName = 2;</code>
       */
      public Builder setLevelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        levelName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.RequestRateLevel)
    }

    // @@protoc_insertion_point(class_scope:leruka.RequestRateLevel)
    private static final RequestRateLevel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestRateLevel();
    }

    public static RequestRateLevel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestRateLevel>
        PARSER = new com.google.protobuf.AbstractParser<RequestRateLevel>() {
      public RequestRateLevel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RequestRateLevel(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RequestRateLevel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestRateLevel> getParserForType() {
      return PARSER;
    }

    public RequestRateLevel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseRateLevelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.ResponseRateLevel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    java.util.List<ErrorCodes.ErrorCode> getErrorCodeList();
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    int getErrorCodeCount();
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    ErrorCodes.ErrorCode getErrorCode(int index);
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    java.util.List<Integer>
    getErrorCodeValueList();
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    int getErrorCodeValue(int index);
  }
  /**
   * Protobuf type {@code leruka.ResponseRateLevel}
   */
  public  static final class ResponseRateLevel extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.ResponseRateLevel)
      ResponseRateLevelOrBuilder {
    // Use ResponseRateLevel.newBuilder() to construct.
    private ResponseRateLevel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResponseRateLevel() {
      success_ = false;
      errorCode_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseRateLevel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                errorCode_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              errorCode_.add(rawValue);
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  errorCode_ = new java.util.ArrayList<Integer>();
                  mutable_bitField0_ |= 0x00000002;
                }
                errorCode_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          errorCode_ = java.util.Collections.unmodifiableList(errorCode_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Rating.internal_static_leruka_ResponseRateLevel_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Rating.internal_static_leruka_ResponseRateLevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseRateLevel.class, Builder.class);
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private java.util.List<Integer> errorCode_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        Integer, ErrorCodes.ErrorCode> errorCode_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                Integer, ErrorCodes.ErrorCode>() {
              public ErrorCodes.ErrorCode convert(Integer from) {
                ErrorCodes.ErrorCode result = ErrorCodes.ErrorCode.valueOf(from);
                return result == null ? ErrorCodes.ErrorCode.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    public java.util.List<ErrorCodes.ErrorCode> getErrorCodeList() {
      return new com.google.protobuf.Internal.ListAdapter<
          Integer, ErrorCodes.ErrorCode>(errorCode_, errorCode_converter_);
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    public int getErrorCodeCount() {
      return errorCode_.size();
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    public ErrorCodes.ErrorCode getErrorCode(int index) {
      return errorCode_converter_.convert(errorCode_.get(index));
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    public java.util.List<Integer>
    getErrorCodeValueList() {
      return errorCode_;
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
     */
    public int getErrorCodeValue(int index) {
      return errorCode_.get(index);
    }
    private int errorCodeMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (getErrorCodeList().size() > 0) {
        output.writeRawVarint32(34);
        output.writeRawVarint32(errorCodeMemoizedSerializedSize);
      }
      for (int i = 0; i < errorCode_.size(); i++) {
        output.writeEnumNoTag(errorCode_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < errorCode_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(errorCode_.get(i));
        }
        size += dataSize;
        if (!getErrorCodeList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeRawVarint32Size(dataSize);
        }errorCodeMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ResponseRateLevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseRateLevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseRateLevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseRateLevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseRateLevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseRateLevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ResponseRateLevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ResponseRateLevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ResponseRateLevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ResponseRateLevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResponseRateLevel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.ResponseRateLevel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.ResponseRateLevel)
        ResponseRateLevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Rating.internal_static_leruka_ResponseRateLevel_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Rating.internal_static_leruka_ResponseRateLevel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseRateLevel.class, Builder.class);
      }

      // Construct using com.leruka.protobuf.Rating.ResponseRateLevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        errorCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Rating.internal_static_leruka_ResponseRateLevel_descriptor;
      }

      public ResponseRateLevel getDefaultInstanceForType() {
        return ResponseRateLevel.getDefaultInstance();
      }

      public ResponseRateLevel build() {
        ResponseRateLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ResponseRateLevel buildPartial() {
        ResponseRateLevel result = new ResponseRateLevel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.success_ = success_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          errorCode_ = java.util.Collections.unmodifiableList(errorCode_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.errorCode_ = errorCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseRateLevel) {
          return mergeFrom((ResponseRateLevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseRateLevel other) {
        if (other == ResponseRateLevel.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.errorCode_.isEmpty()) {
          if (errorCode_.isEmpty()) {
            errorCode_ = other.errorCode_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureErrorCodeIsMutable();
            errorCode_.addAll(other.errorCode_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseRateLevel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseRateLevel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.util.List<Integer> errorCode_ =
        java.util.Collections.emptyList();
      private void ensureErrorCodeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          errorCode_ = new java.util.ArrayList<Integer>(errorCode_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public java.util.List<ErrorCodes.ErrorCode> getErrorCodeList() {
        return new com.google.protobuf.Internal.ListAdapter<
            Integer, ErrorCodes.ErrorCode>(errorCode_, errorCode_converter_);
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public int getErrorCodeCount() {
        return errorCode_.size();
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public ErrorCodes.ErrorCode getErrorCode(int index) {
        return errorCode_converter_.convert(errorCode_.get(index));
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public Builder setErrorCode(
          int index, ErrorCodes.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorCodeIsMutable();
        errorCode_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public Builder addErrorCode(ErrorCodes.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorCodeIsMutable();
        errorCode_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public Builder addAllErrorCode(
          Iterable<? extends ErrorCodes.ErrorCode> values) {
        ensureErrorCodeIsMutable();
        for (ErrorCodes.ErrorCode value : values) {
          errorCode_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public Builder clearErrorCode() {
        errorCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public java.util.List<Integer>
      getErrorCodeValueList() {
        return java.util.Collections.unmodifiableList(errorCode_);
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public int getErrorCodeValue(int index) {
        return errorCode_.get(index);
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public Builder setErrorCodeValue(
          int index, int value) {
        ensureErrorCodeIsMutable();
        errorCode_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public Builder addErrorCodeValue(int value) {
        ensureErrorCodeIsMutable();
        errorCode_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 4;</code>
       */
      public Builder addAllErrorCodeValue(
          Iterable<Integer> values) {
        ensureErrorCodeIsMutable();
        for (int value : values) {
          errorCode_.add(value);
        }
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.ResponseRateLevel)
    }

    // @@protoc_insertion_point(class_scope:leruka.ResponseRateLevel)
    private static final ResponseRateLevel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResponseRateLevel();
    }

    public static ResponseRateLevel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseRateLevel>
        PARSER = new com.google.protobuf.AbstractParser<ResponseRateLevel>() {
      public ResponseRateLevel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ResponseRateLevel(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ResponseRateLevel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResponseRateLevel> getParserForType() {
      return PARSER;
    }

    public ResponseRateLevel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_RequestRateLevel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_RequestRateLevel_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_ResponseRateLevel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_ResponseRateLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014rating.proto\022\006leruka\032\020errorCodes.proto" +
      "\"8\n\020RequestRateLevel\022\021\n\tsessionID\030\001 \001(\t\022" +
      "\021\n\tlevelName\030\002 \001(\t\"J\n\021ResponseRateLevel\022" +
      "\017\n\007success\030\001 \001(\010\022$\n\terrorCode\030\004 \003(\0162\021.le" +
      "ruka.ErrorCodeB\025\n\023com.leruka.protobufb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ErrorCodes.getDescriptor(),
        }, assigner);
    internal_static_leruka_RequestRateLevel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_leruka_RequestRateLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_RequestRateLevel_descriptor,
        new String[] { "SessionID", "LevelName", });
    internal_static_leruka_ResponseRateLevel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_leruka_ResponseRateLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_ResponseRateLevel_descriptor,
        new String[] { "Success", "ErrorCode", });
    ErrorCodes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
