// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.leruka.protobuf;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.RequestLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code leruka.RequestLogin}
   *
   * <pre>
   * The request to log in on the server
   * </pre>
   */
  public  static final class RequestLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.RequestLogin)
      RequestLoginOrBuilder {
    // Use RequestLogin.newBuilder() to construct.
    private RequestLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RequestLogin() {
      name_ = "";
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leruka.protobuf.User.internal_static_leruka_RequestLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leruka.protobuf.User.internal_static_leruka_RequestLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leruka.protobuf.User.RequestLogin.class, com.leruka.protobuf.User.RequestLogin.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, password_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, password_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.leruka.protobuf.User.RequestLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.User.RequestLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.User.RequestLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.User.RequestLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.User.RequestLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.User.RequestLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.User.RequestLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leruka.protobuf.User.RequestLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.User.RequestLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.User.RequestLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leruka.protobuf.User.RequestLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.RequestLogin}
     *
     * <pre>
     * The request to log in on the server
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.RequestLogin)
        com.leruka.protobuf.User.RequestLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leruka.protobuf.User.internal_static_leruka_RequestLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leruka.protobuf.User.internal_static_leruka_RequestLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leruka.protobuf.User.RequestLogin.class, com.leruka.protobuf.User.RequestLogin.Builder.class);
      }

      // Construct using com.leruka.protobuf.User.RequestLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leruka.protobuf.User.internal_static_leruka_RequestLogin_descriptor;
      }

      public com.leruka.protobuf.User.RequestLogin getDefaultInstanceForType() {
        return com.leruka.protobuf.User.RequestLogin.getDefaultInstance();
      }

      public com.leruka.protobuf.User.RequestLogin build() {
        com.leruka.protobuf.User.RequestLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leruka.protobuf.User.RequestLogin buildPartial() {
        com.leruka.protobuf.User.RequestLogin result = new com.leruka.protobuf.User.RequestLogin(this);
        result.name_ = name_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leruka.protobuf.User.RequestLogin) {
          return mergeFrom((com.leruka.protobuf.User.RequestLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leruka.protobuf.User.RequestLogin other) {
        if (other == com.leruka.protobuf.User.RequestLogin.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leruka.protobuf.User.RequestLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leruka.protobuf.User.RequestLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.RequestLogin)
    }

    // @@protoc_insertion_point(class_scope:leruka.RequestLogin)
    private static final com.leruka.protobuf.User.RequestLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leruka.protobuf.User.RequestLogin();
    }

    public static com.leruka.protobuf.User.RequestLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestLogin>
        PARSER = new com.google.protobuf.AbstractParser<RequestLogin>() {
      public RequestLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RequestLogin(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RequestLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestLogin> getParserForType() {
      return PARSER;
    }

    public com.leruka.protobuf.User.RequestLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.RequestRegister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code leruka.RequestRegister}
   *
   * <pre>
   * The request to register on the server
   * </pre>
   */
  public  static final class RequestRegister extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.RequestRegister)
      RequestRegisterOrBuilder {
    // Use RequestRegister.newBuilder() to construct.
    private RequestRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RequestRegister() {
      name_ = "";
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestRegister(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leruka.protobuf.User.internal_static_leruka_RequestRegister_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leruka.protobuf.User.internal_static_leruka_RequestRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leruka.protobuf.User.RequestRegister.class, com.leruka.protobuf.User.RequestRegister.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, password_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, password_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.leruka.protobuf.User.RequestRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.User.RequestRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.User.RequestRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.User.RequestRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.User.RequestRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.User.RequestRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.User.RequestRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leruka.protobuf.User.RequestRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.User.RequestRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.User.RequestRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leruka.protobuf.User.RequestRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.RequestRegister}
     *
     * <pre>
     * The request to register on the server
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.RequestRegister)
        com.leruka.protobuf.User.RequestRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leruka.protobuf.User.internal_static_leruka_RequestRegister_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leruka.protobuf.User.internal_static_leruka_RequestRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leruka.protobuf.User.RequestRegister.class, com.leruka.protobuf.User.RequestRegister.Builder.class);
      }

      // Construct using com.leruka.protobuf.User.RequestRegister.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leruka.protobuf.User.internal_static_leruka_RequestRegister_descriptor;
      }

      public com.leruka.protobuf.User.RequestRegister getDefaultInstanceForType() {
        return com.leruka.protobuf.User.RequestRegister.getDefaultInstance();
      }

      public com.leruka.protobuf.User.RequestRegister build() {
        com.leruka.protobuf.User.RequestRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leruka.protobuf.User.RequestRegister buildPartial() {
        com.leruka.protobuf.User.RequestRegister result = new com.leruka.protobuf.User.RequestRegister(this);
        result.name_ = name_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leruka.protobuf.User.RequestRegister) {
          return mergeFrom((com.leruka.protobuf.User.RequestRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leruka.protobuf.User.RequestRegister other) {
        if (other == com.leruka.protobuf.User.RequestRegister.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leruka.protobuf.User.RequestRegister parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leruka.protobuf.User.RequestRegister) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.RequestRegister)
    }

    // @@protoc_insertion_point(class_scope:leruka.RequestRegister)
    private static final com.leruka.protobuf.User.RequestRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leruka.protobuf.User.RequestRegister();
    }

    public static com.leruka.protobuf.User.RequestRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestRegister>
        PARSER = new com.google.protobuf.AbstractParser<RequestRegister>() {
      public RequestRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new RequestRegister(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<RequestRegister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestRegister> getParserForType() {
      return PARSER;
    }

    public com.leruka.protobuf.User.RequestRegister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.ResponseLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <code>optional string sessionID = 2;</code>
     */
    java.lang.String getSessionID();
    /**
     * <code>optional string sessionID = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessionIDBytes();

    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    java.util.List<com.leruka.protobuf.ErrorCodes.ErrorCode> getErrorCodeList();
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    int getErrorCodeCount();
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    com.leruka.protobuf.ErrorCodes.ErrorCode getErrorCode(int index);
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    java.util.List<java.lang.Integer>
    getErrorCodeValueList();
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    int getErrorCodeValue(int index);
  }
  /**
   * Protobuf type {@code leruka.ResponseLogin}
   *
   * <pre>
   * The response when the user has tried to log in on the server
   * </pre>
   */
  public  static final class ResponseLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.ResponseLogin)
      ResponseLoginOrBuilder {
    // Use ResponseLogin.newBuilder() to construct.
    private ResponseLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResponseLogin() {
      success_ = false;
      sessionID_ = "";
      errorCode_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionID_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                errorCode_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              errorCode_.add(rawValue);
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  errorCode_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000004;
                }
                errorCode_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          errorCode_ = java.util.Collections.unmodifiableList(errorCode_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leruka.protobuf.User.internal_static_leruka_ResponseLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leruka.protobuf.User.internal_static_leruka_ResponseLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leruka.protobuf.User.ResponseLogin.class, com.leruka.protobuf.User.ResponseLogin.Builder.class);
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private volatile java.lang.Object sessionID_;
    /**
     * <code>optional string sessionID = 2;</code>
     */
    public java.lang.String getSessionID() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionID_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sessionID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIDBytes() {
      java.lang.Object ref = sessionID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORCODE_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> errorCode_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, com.leruka.protobuf.ErrorCodes.ErrorCode> errorCode_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, com.leruka.protobuf.ErrorCodes.ErrorCode>() {
              public com.leruka.protobuf.ErrorCodes.ErrorCode convert(java.lang.Integer from) {
                com.leruka.protobuf.ErrorCodes.ErrorCode result = com.leruka.protobuf.ErrorCodes.ErrorCode.valueOf(from);
                return result == null ? com.leruka.protobuf.ErrorCodes.ErrorCode.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public java.util.List<com.leruka.protobuf.ErrorCodes.ErrorCode> getErrorCodeList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.leruka.protobuf.ErrorCodes.ErrorCode>(errorCode_, errorCode_converter_);
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public int getErrorCodeCount() {
      return errorCode_.size();
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public com.leruka.protobuf.ErrorCodes.ErrorCode getErrorCode(int index) {
      return errorCode_converter_.convert(errorCode_.get(index));
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public java.util.List<java.lang.Integer>
    getErrorCodeValueList() {
      return errorCode_;
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public int getErrorCodeValue(int index) {
      return errorCode_.get(index);
    }
    private int errorCodeMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getSessionIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, sessionID_);
      }
      if (getErrorCodeList().size() > 0) {
        output.writeRawVarint32(26);
        output.writeRawVarint32(errorCodeMemoizedSerializedSize);
      }
      for (int i = 0; i < errorCode_.size(); i++) {
        output.writeEnumNoTag(errorCode_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getSessionIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sessionID_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < errorCode_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(errorCode_.get(i));
        }
        size += dataSize;
        if (!getErrorCodeList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeRawVarint32Size(dataSize);
        }errorCodeMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.leruka.protobuf.User.ResponseLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.User.ResponseLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.User.ResponseLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.User.ResponseLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.User.ResponseLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.User.ResponseLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.User.ResponseLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leruka.protobuf.User.ResponseLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.User.ResponseLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.User.ResponseLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leruka.protobuf.User.ResponseLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.ResponseLogin}
     *
     * <pre>
     * The response when the user has tried to log in on the server
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.ResponseLogin)
        com.leruka.protobuf.User.ResponseLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leruka.protobuf.User.internal_static_leruka_ResponseLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leruka.protobuf.User.internal_static_leruka_ResponseLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leruka.protobuf.User.ResponseLogin.class, com.leruka.protobuf.User.ResponseLogin.Builder.class);
      }

      // Construct using com.leruka.protobuf.User.ResponseLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        sessionID_ = "";

        errorCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leruka.protobuf.User.internal_static_leruka_ResponseLogin_descriptor;
      }

      public com.leruka.protobuf.User.ResponseLogin getDefaultInstanceForType() {
        return com.leruka.protobuf.User.ResponseLogin.getDefaultInstance();
      }

      public com.leruka.protobuf.User.ResponseLogin build() {
        com.leruka.protobuf.User.ResponseLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leruka.protobuf.User.ResponseLogin buildPartial() {
        com.leruka.protobuf.User.ResponseLogin result = new com.leruka.protobuf.User.ResponseLogin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.success_ = success_;
        result.sessionID_ = sessionID_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          errorCode_ = java.util.Collections.unmodifiableList(errorCode_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.errorCode_ = errorCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leruka.protobuf.User.ResponseLogin) {
          return mergeFrom((com.leruka.protobuf.User.ResponseLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leruka.protobuf.User.ResponseLogin other) {
        if (other == com.leruka.protobuf.User.ResponseLogin.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getSessionID().isEmpty()) {
          sessionID_ = other.sessionID_;
          onChanged();
        }
        if (!other.errorCode_.isEmpty()) {
          if (errorCode_.isEmpty()) {
            errorCode_ = other.errorCode_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureErrorCodeIsMutable();
            errorCode_.addAll(other.errorCode_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leruka.protobuf.User.ResponseLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leruka.protobuf.User.ResponseLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object sessionID_ = "";
      /**
       * <code>optional string sessionID = 2;</code>
       */
      public java.lang.String getSessionID() {
        java.lang.Object ref = sessionID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIDBytes() {
        java.lang.Object ref = sessionID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionID = 2;</code>
       */
      public Builder setSessionID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionID = 2;</code>
       */
      public Builder clearSessionID() {
        
        sessionID_ = getDefaultInstance().getSessionID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionID = 2;</code>
       */
      public Builder setSessionIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionID_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> errorCode_ =
        java.util.Collections.emptyList();
      private void ensureErrorCodeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          errorCode_ = new java.util.ArrayList<java.lang.Integer>(errorCode_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public java.util.List<com.leruka.protobuf.ErrorCodes.ErrorCode> getErrorCodeList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, com.leruka.protobuf.ErrorCodes.ErrorCode>(errorCode_, errorCode_converter_);
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public int getErrorCodeCount() {
        return errorCode_.size();
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public com.leruka.protobuf.ErrorCodes.ErrorCode getErrorCode(int index) {
        return errorCode_converter_.convert(errorCode_.get(index));
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder setErrorCode(
          int index, com.leruka.protobuf.ErrorCodes.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorCodeIsMutable();
        errorCode_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder addErrorCode(com.leruka.protobuf.ErrorCodes.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorCodeIsMutable();
        errorCode_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder addAllErrorCode(
          java.lang.Iterable<? extends com.leruka.protobuf.ErrorCodes.ErrorCode> values) {
        ensureErrorCodeIsMutable();
        for (com.leruka.protobuf.ErrorCodes.ErrorCode value : values) {
          errorCode_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder clearErrorCode() {
        errorCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public java.util.List<java.lang.Integer>
      getErrorCodeValueList() {
        return java.util.Collections.unmodifiableList(errorCode_);
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public int getErrorCodeValue(int index) {
        return errorCode_.get(index);
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder setErrorCodeValue(
          int index, int value) {
        ensureErrorCodeIsMutable();
        errorCode_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder addErrorCodeValue(int value) {
        ensureErrorCodeIsMutable();
        errorCode_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder addAllErrorCodeValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureErrorCodeIsMutable();
        for (int value : values) {
          errorCode_.add(value);
        }
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.ResponseLogin)
    }

    // @@protoc_insertion_point(class_scope:leruka.ResponseLogin)
    private static final com.leruka.protobuf.User.ResponseLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leruka.protobuf.User.ResponseLogin();
    }

    public static com.leruka.protobuf.User.ResponseLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseLogin>
        PARSER = new com.google.protobuf.AbstractParser<ResponseLogin>() {
      public ResponseLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ResponseLogin(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ResponseLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseLogin> getParserForType() {
      return PARSER;
    }

    public com.leruka.protobuf.User.ResponseLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:leruka.ResponseRegister)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <code>optional .leruka.ResponseLogin login = 2;</code>
     */
    boolean hasLogin();
    /**
     * <code>optional .leruka.ResponseLogin login = 2;</code>
     */
    com.leruka.protobuf.User.ResponseLogin getLogin();
    /**
     * <code>optional .leruka.ResponseLogin login = 2;</code>
     */
    com.leruka.protobuf.User.ResponseLoginOrBuilder getLoginOrBuilder();

    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    java.util.List<com.leruka.protobuf.ErrorCodes.ErrorCode> getErrorCodeList();
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    int getErrorCodeCount();
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    com.leruka.protobuf.ErrorCodes.ErrorCode getErrorCode(int index);
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    java.util.List<java.lang.Integer>
    getErrorCodeValueList();
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    int getErrorCodeValue(int index);
  }
  /**
   * Protobuf type {@code leruka.ResponseRegister}
   *
   * <pre>
   * The response when the user has tried to register on the server
   * </pre>
   */
  public  static final class ResponseRegister extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:leruka.ResponseRegister)
      ResponseRegisterOrBuilder {
    // Use ResponseRegister.newBuilder() to construct.
    private ResponseRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResponseRegister() {
      success_ = false;
      errorCode_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseRegister(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              com.leruka.protobuf.User.ResponseLogin.Builder subBuilder = null;
              if (login_ != null) {
                subBuilder = login_.toBuilder();
              }
              login_ = input.readMessage(com.leruka.protobuf.User.ResponseLogin.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(login_);
                login_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                errorCode_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              errorCode_.add(rawValue);
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  errorCode_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000004;
                }
                errorCode_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          errorCode_ = java.util.Collections.unmodifiableList(errorCode_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leruka.protobuf.User.internal_static_leruka_ResponseRegister_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leruka.protobuf.User.internal_static_leruka_ResponseRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leruka.protobuf.User.ResponseRegister.class, com.leruka.protobuf.User.ResponseRegister.Builder.class);
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int LOGIN_FIELD_NUMBER = 2;
    private com.leruka.protobuf.User.ResponseLogin login_;
    /**
     * <code>optional .leruka.ResponseLogin login = 2;</code>
     */
    public boolean hasLogin() {
      return login_ != null;
    }
    /**
     * <code>optional .leruka.ResponseLogin login = 2;</code>
     */
    public com.leruka.protobuf.User.ResponseLogin getLogin() {
      return login_ == null ? com.leruka.protobuf.User.ResponseLogin.getDefaultInstance() : login_;
    }
    /**
     * <code>optional .leruka.ResponseLogin login = 2;</code>
     */
    public com.leruka.protobuf.User.ResponseLoginOrBuilder getLoginOrBuilder() {
      return getLogin();
    }

    public static final int ERRORCODE_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> errorCode_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, com.leruka.protobuf.ErrorCodes.ErrorCode> errorCode_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, com.leruka.protobuf.ErrorCodes.ErrorCode>() {
              public com.leruka.protobuf.ErrorCodes.ErrorCode convert(java.lang.Integer from) {
                com.leruka.protobuf.ErrorCodes.ErrorCode result = com.leruka.protobuf.ErrorCodes.ErrorCode.valueOf(from);
                return result == null ? com.leruka.protobuf.ErrorCodes.ErrorCode.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public java.util.List<com.leruka.protobuf.ErrorCodes.ErrorCode> getErrorCodeList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.leruka.protobuf.ErrorCodes.ErrorCode>(errorCode_, errorCode_converter_);
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public int getErrorCodeCount() {
      return errorCode_.size();
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public com.leruka.protobuf.ErrorCodes.ErrorCode getErrorCode(int index) {
      return errorCode_converter_.convert(errorCode_.get(index));
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public java.util.List<java.lang.Integer>
    getErrorCodeValueList() {
      return errorCode_;
    }
    /**
     * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
     */
    public int getErrorCodeValue(int index) {
      return errorCode_.get(index);
    }
    private int errorCodeMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (login_ != null) {
        output.writeMessage(2, getLogin());
      }
      if (getErrorCodeList().size() > 0) {
        output.writeRawVarint32(26);
        output.writeRawVarint32(errorCodeMemoizedSerializedSize);
      }
      for (int i = 0; i < errorCode_.size(); i++) {
        output.writeEnumNoTag(errorCode_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (login_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLogin());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < errorCode_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(errorCode_.get(i));
        }
        size += dataSize;
        if (!getErrorCodeList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeRawVarint32Size(dataSize);
        }errorCodeMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.leruka.protobuf.User.ResponseRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.User.ResponseRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.User.ResponseRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leruka.protobuf.User.ResponseRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leruka.protobuf.User.ResponseRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.User.ResponseRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.User.ResponseRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.leruka.protobuf.User.ResponseRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.leruka.protobuf.User.ResponseRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.leruka.protobuf.User.ResponseRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leruka.protobuf.User.ResponseRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code leruka.ResponseRegister}
     *
     * <pre>
     * The response when the user has tried to register on the server
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:leruka.ResponseRegister)
        com.leruka.protobuf.User.ResponseRegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leruka.protobuf.User.internal_static_leruka_ResponseRegister_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leruka.protobuf.User.internal_static_leruka_ResponseRegister_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leruka.protobuf.User.ResponseRegister.class, com.leruka.protobuf.User.ResponseRegister.Builder.class);
      }

      // Construct using com.leruka.protobuf.User.ResponseRegister.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        if (loginBuilder_ == null) {
          login_ = null;
        } else {
          login_ = null;
          loginBuilder_ = null;
        }
        errorCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leruka.protobuf.User.internal_static_leruka_ResponseRegister_descriptor;
      }

      public com.leruka.protobuf.User.ResponseRegister getDefaultInstanceForType() {
        return com.leruka.protobuf.User.ResponseRegister.getDefaultInstance();
      }

      public com.leruka.protobuf.User.ResponseRegister build() {
        com.leruka.protobuf.User.ResponseRegister result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leruka.protobuf.User.ResponseRegister buildPartial() {
        com.leruka.protobuf.User.ResponseRegister result = new com.leruka.protobuf.User.ResponseRegister(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.success_ = success_;
        if (loginBuilder_ == null) {
          result.login_ = login_;
        } else {
          result.login_ = loginBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          errorCode_ = java.util.Collections.unmodifiableList(errorCode_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.errorCode_ = errorCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leruka.protobuf.User.ResponseRegister) {
          return mergeFrom((com.leruka.protobuf.User.ResponseRegister)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leruka.protobuf.User.ResponseRegister other) {
        if (other == com.leruka.protobuf.User.ResponseRegister.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.hasLogin()) {
          mergeLogin(other.getLogin());
        }
        if (!other.errorCode_.isEmpty()) {
          if (errorCode_.isEmpty()) {
            errorCode_ = other.errorCode_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureErrorCodeIsMutable();
            errorCode_.addAll(other.errorCode_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leruka.protobuf.User.ResponseRegister parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leruka.protobuf.User.ResponseRegister) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private com.leruka.protobuf.User.ResponseLogin login_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.leruka.protobuf.User.ResponseLogin, com.leruka.protobuf.User.ResponseLogin.Builder, com.leruka.protobuf.User.ResponseLoginOrBuilder> loginBuilder_;
      /**
       * <code>optional .leruka.ResponseLogin login = 2;</code>
       */
      public boolean hasLogin() {
        return loginBuilder_ != null || login_ != null;
      }
      /**
       * <code>optional .leruka.ResponseLogin login = 2;</code>
       */
      public com.leruka.protobuf.User.ResponseLogin getLogin() {
        if (loginBuilder_ == null) {
          return login_ == null ? com.leruka.protobuf.User.ResponseLogin.getDefaultInstance() : login_;
        } else {
          return loginBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .leruka.ResponseLogin login = 2;</code>
       */
      public Builder setLogin(com.leruka.protobuf.User.ResponseLogin value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          login_ = value;
          onChanged();
        } else {
          loginBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .leruka.ResponseLogin login = 2;</code>
       */
      public Builder setLogin(
          com.leruka.protobuf.User.ResponseLogin.Builder builderForValue) {
        if (loginBuilder_ == null) {
          login_ = builderForValue.build();
          onChanged();
        } else {
          loginBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .leruka.ResponseLogin login = 2;</code>
       */
      public Builder mergeLogin(com.leruka.protobuf.User.ResponseLogin value) {
        if (loginBuilder_ == null) {
          if (login_ != null) {
            login_ =
              com.leruka.protobuf.User.ResponseLogin.newBuilder(login_).mergeFrom(value).buildPartial();
          } else {
            login_ = value;
          }
          onChanged();
        } else {
          loginBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .leruka.ResponseLogin login = 2;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          login_ = null;
          onChanged();
        } else {
          login_ = null;
          loginBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .leruka.ResponseLogin login = 2;</code>
       */
      public com.leruka.protobuf.User.ResponseLogin.Builder getLoginBuilder() {
        
        onChanged();
        return getLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .leruka.ResponseLogin login = 2;</code>
       */
      public com.leruka.protobuf.User.ResponseLoginOrBuilder getLoginOrBuilder() {
        if (loginBuilder_ != null) {
          return loginBuilder_.getMessageOrBuilder();
        } else {
          return login_ == null ?
              com.leruka.protobuf.User.ResponseLogin.getDefaultInstance() : login_;
        }
      }
      /**
       * <code>optional .leruka.ResponseLogin login = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.leruka.protobuf.User.ResponseLogin, com.leruka.protobuf.User.ResponseLogin.Builder, com.leruka.protobuf.User.ResponseLoginOrBuilder> 
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          loginBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.leruka.protobuf.User.ResponseLogin, com.leruka.protobuf.User.ResponseLogin.Builder, com.leruka.protobuf.User.ResponseLoginOrBuilder>(
                  getLogin(),
                  getParentForChildren(),
                  isClean());
          login_ = null;
        }
        return loginBuilder_;
      }

      private java.util.List<java.lang.Integer> errorCode_ =
        java.util.Collections.emptyList();
      private void ensureErrorCodeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          errorCode_ = new java.util.ArrayList<java.lang.Integer>(errorCode_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public java.util.List<com.leruka.protobuf.ErrorCodes.ErrorCode> getErrorCodeList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, com.leruka.protobuf.ErrorCodes.ErrorCode>(errorCode_, errorCode_converter_);
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public int getErrorCodeCount() {
        return errorCode_.size();
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public com.leruka.protobuf.ErrorCodes.ErrorCode getErrorCode(int index) {
        return errorCode_converter_.convert(errorCode_.get(index));
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder setErrorCode(
          int index, com.leruka.protobuf.ErrorCodes.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorCodeIsMutable();
        errorCode_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder addErrorCode(com.leruka.protobuf.ErrorCodes.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureErrorCodeIsMutable();
        errorCode_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder addAllErrorCode(
          java.lang.Iterable<? extends com.leruka.protobuf.ErrorCodes.ErrorCode> values) {
        ensureErrorCodeIsMutable();
        for (com.leruka.protobuf.ErrorCodes.ErrorCode value : values) {
          errorCode_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder clearErrorCode() {
        errorCode_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public java.util.List<java.lang.Integer>
      getErrorCodeValueList() {
        return java.util.Collections.unmodifiableList(errorCode_);
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public int getErrorCodeValue(int index) {
        return errorCode_.get(index);
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder setErrorCodeValue(
          int index, int value) {
        ensureErrorCodeIsMutable();
        errorCode_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder addErrorCodeValue(int value) {
        ensureErrorCodeIsMutable();
        errorCode_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .leruka.ErrorCode errorCode = 3;</code>
       */
      public Builder addAllErrorCodeValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureErrorCodeIsMutable();
        for (int value : values) {
          errorCode_.add(value);
        }
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:leruka.ResponseRegister)
    }

    // @@protoc_insertion_point(class_scope:leruka.ResponseRegister)
    private static final com.leruka.protobuf.User.ResponseRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leruka.protobuf.User.ResponseRegister();
    }

    public static com.leruka.protobuf.User.ResponseRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseRegister>
        PARSER = new com.google.protobuf.AbstractParser<ResponseRegister>() {
      public ResponseRegister parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ResponseRegister(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ResponseRegister> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseRegister> getParserForType() {
      return PARSER;
    }

    public com.leruka.protobuf.User.ResponseRegister getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_RequestLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_RequestLogin_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_RequestRegister_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_RequestRegister_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_ResponseLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_ResponseLogin_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_leruka_ResponseRegister_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_leruka_ResponseRegister_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\006leruka\032\020errorCodes.proto\"." +
      "\n\014RequestLogin\022\014\n\004name\030\001 \001(\t\022\020\n\010password" +
      "\030\002 \001(\t\"1\n\017RequestRegister\022\014\n\004name\030\001 \001(\t\022" +
      "\020\n\010password\030\002 \001(\t\"Y\n\rResponseLogin\022\017\n\007su" +
      "ccess\030\001 \001(\010\022\021\n\tsessionID\030\002 \001(\t\022$\n\terrorC" +
      "ode\030\003 \003(\0162\021.leruka.ErrorCode\"o\n\020Response" +
      "Register\022\017\n\007success\030\001 \001(\010\022$\n\005login\030\002 \001(\013" +
      "2\025.leruka.ResponseLogin\022$\n\terrorCode\030\003 \003" +
      "(\0162\021.leruka.ErrorCodeB\025\n\023com.leruka.prot" +
      "obufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.leruka.protobuf.ErrorCodes.getDescriptor(),
        }, assigner);
    internal_static_leruka_RequestLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_leruka_RequestLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_RequestLogin_descriptor,
        new java.lang.String[] { "Name", "Password", });
    internal_static_leruka_RequestRegister_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_leruka_RequestRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_RequestRegister_descriptor,
        new java.lang.String[] { "Name", "Password", });
    internal_static_leruka_ResponseLogin_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_leruka_ResponseLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_ResponseLogin_descriptor,
        new java.lang.String[] { "Success", "SessionID", "ErrorCode", });
    internal_static_leruka_ResponseRegister_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_leruka_ResponseRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_leruka_ResponseRegister_descriptor,
        new java.lang.String[] { "Success", "Login", "ErrorCode", });
    com.leruka.protobuf.ErrorCodes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
